### ISSUE TITLE
Compact View

### ISSUE THREAD

**Issue by benyanke** [nextcloud/deck#587]
**Is your feature request related to a problem? Please describe.**
Often on a smaller screen (my daily driver is a 13 inch notebook), I feel like I do a lot of scrolling to get a good general picture.

**Describe the solution you'd like**
Similar to Taiga's zoom levels, I'd like to implement a "compact mode" which changes the CSS to display more tightly packed cards. It's quite nice right now on a large screen, but don't forget some people also use tablets and netbooks!

Here is an example addition to the stylesheet:

```css
/* 
This style is used to make NextCloud board more compact view. to enable, add the 
class 'compact' to div #board
*/

.compact .card .card-assigned-users, .compact .card .card-controls {
  display: none;
}

.compact .card h4 {
  font-size: 9pt;
}

.compact .card .labels li {
  height: 10px;
}

.compact .card {
  margin-bottom: 8px;
}

.compact .card {
  border-bottom: 5px solid #dddddd !important;
}

.compact .card-selected .card.current {
      box-shadow: 0px 0px 7px 0px #555555;
} 

@media (min-width: 481px) {
  .compact  .stack {

    width: 250px;
    min-width: 250px;
  }
}

```

## Before

![image](https://user-images.githubusercontent.com/4274911/44068075-f3f7f3d6-9f3d-11e8-9319-c0250455aa17.png)

## After
![image](https://user-images.githubusercontent.com/4274911/44068063-e21d2f5a-9f3d-11e8-9bee-eb901c411195.png)
